//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSAssembler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMSAssembler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00 ERROR
        ///01 NOP
        ///02 PROGRAM_STOP        16
        ///03 PROGRAM_START       16 32 32 8
        ///04 OBJECT_STOP         T
        ///05 OBJECT_START        T
        ///06 OBJECT_TRIG         T
        ///07 OBJECT_WAIT         T
        ///08 RETURN
        ///// 09 CALL            
        ///0A OBJECT_END          
        ///0B SLEEP
        ///
        ///0C00 PROGRAM_INFO OBJ_STOP       16 16
        ///0C04 PROGRAM_INFO OBJ_START      16 16
        ///0C16 PROGRAM_INFO GET_STATUS     16 8*
        ///0C17 PROGRAM_INFO GET_SPEED      16 32*
        ///0C18 PROGRAM_INFO GET_PRGRESULT  16 8*
        ///// 0C19 PROGRAM_INFO SET_INSTR      
        ///
        ///0D LABEL        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bytecodelist {
            get {
                return ResourceManager.GetString("bytecodelist", resourceCulture);
            }
        }
    }
}
