//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EV3BasicCompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EV3BasicCompiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // -------------------------------------- EXTENSION MODULE: ASSERT -----------------------------------
        ///
        ///subcall ASSERT.FAILED     // SV         TEXT.GETSUBTEXT TEXT.GETSUBTEXTTOEND
        ///{
        ///	IN_S message 252
        ///	DATA32 timer
        ///	
        ///	UI_DRAW CLEAN
        ///	UI_DRAW SELECT_FONT 1
        ///	UI_DRAW TEXT 1 0 16 &apos;ASSERT FAILED&apos;
        ///
        ///	DATA16 y
        ///	MOVE16_16 32 y
        ///	
        ///linesloop:
        ///	DATA16 len	
        ///	STRINGS GET_SIZE message len
        ///	JR_LTEQ16 len 20 lastline
        ///	
        ///	DATAS oneline 32
        ///	CALL TEXT.GETSUBTEXT message 1.0 20.0 oneline
        ///	UI_DRAW TEXT 1 0 y on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Assert {
            get {
                return ResourceManager.GetString("Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------ EV3 MODULE: BUTTONS -------------------------------------------------
        ///
        ///subcall BUTTONS.CURRENT    // S
        ///{
        ///	OUT_S result 8
        ///
        ///	DATA8 ispressed
        ///	
        ///	STRINGS DUPLICATE &apos;&apos; result	
        ///	
        ///	UI_BUTTON PRESSED 1 ispressed
        ///	JR_EQ8 ispressed 0 not_up
        ///	STRINGS ADD result &apos;U&apos; result
        ///not_up:
        ///	UI_BUTTON PRESSED 2 ispressed
        ///	JR_EQ8 ispressed 0 not_enter
        ///	STRINGS ADD result &apos;E&apos; result
        ///not_enter:
        ///	UI_BUTTON PRESSED 3 ispressed
        ///	JR_EQ8 ispressed 0 not_down
        ///	STRINGS ADD  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------ EV3 MODULE: EV3 -------------------------------------------------
        ///
        ///subcall EV3.SETLEDCOLOR    // SSV
        ///{
        ///	IN_S color 8		// only receive first 7 characters
        ///	IN_S effect 8       // only receive first 7 characters
        ///	
        ///	ARRAY8 color_1 4	// split up to be able to do some operations with 4 bytes each
        ///	ARRAY8 color_2 4
        ///	ARRAY8 effect_1 4
        ///	ARRAY8 effect_2 4
        ///
        ///	STRINGS DUPLICATE color color_1
        ///	STRINGS DUPLICATE effect effect_1	
        ///	AND8888_32 color_1 -538976289 col [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EV3 {
            get {
                return ResourceManager.GetString("EV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------ EV3 MODULE: LCD -------------------------------------------------
        ///
        ///DATA32 STOPLCDUPDATE
        ///
        ///inline LCD.STOPUPDATE    // V
        ///{
        ///	MOVE32_32 1 STOPLCDUPDATE
        ///}
        ///
        ///inline LCD.UPDATE  // V
        ///{
        ///	MOVE32_32 0 STOPLCDUPDATE
        ///	UI_DRAW UPDATE
        ///}
        ///
        ///subcall LCD.CLEAR   // V
        ///{
        ///	UI_DRAW(TOPLINE,0)
        ///	UI_DRAW(CLEAN)
        ///	
        ///	JR_NEQ32 0 STOPLCDUPDATE skipupdate
        ///	UI_DRAW UPDATE
        ///skipupdate:
        ///}
        ///
        ///subcall LCD.RECT      // FFFFFV
        ///{
        ///	IN_F col
        ///	IN_F x
        ///	IN_F y
        ///	IN_F w
        ///	IN_F h	
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LCD {
            get {
                return ResourceManager.GetString("LCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ---------------------------------------- BASIC MODULE: MATH ---------------------------------------
        ///
        ///inline MATH.PI              // F
        ///{
        ///	MOVEF_F 3.1415926535897932384 :0
        ///}
        ///
        ///inline MATH.ABS             // FF
        ///{
        ///	MATH ABS :0 :1
        ///}
        ///inline MATH.ARCCOS          // FF
        ///{
        ///	DATAF tmpf:#
        ///	MATH ACOS :0 tmpf:#
        ///	DIVF tmpf:# 57.295779513082 :1
        ///}
        ///inline MATH.ARCSIN          // FF
        ///{
        ///	DATAF tmpf:#
        ///	MATH ASIN :0 tmpf:#
        ///	DIVF tmpf:# 57.295779513082 :1
        ///}
        ///inline MATH.ARCTAN          // FF
        ///{
        ///	DATAF tmpf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Math {
            get {
                return ResourceManager.GetString("Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------ EV3 MODULE: MOTOR ----------------------------------------------
        ///
        ///subcall MOTORDECODEPORTSDESCRIPTOR  //  V
        ///{
        ///	IN_S descriptor 8
        ///	OUT_8 layer
        ///	OUT_8 nos
        ///
        ///	DATA8 i 
        ///	DATA8 c
        ///
        ///	MOVE8_8 0 layer
        ///	MOVE8_8 0 nos	
        ///	MOVE8_8 0 i
        ///loop:
        ///	READ8 descriptor i c
        ///	JR_EQ8 c 0 decoding_end
        ///	
        ///	JR_LT8 c 65 no_uppercase_port
        ///	JR_GT8 c 68 no_uppercase_port
        ///	SUB8 c 65 c
        ///	RL8  1 c c
        ///	OR8  nos c nos
        ///	JR loop_end
        ///no_uppercase_port:
        ///	JR_LT8 c 97 no_lowercase_port        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------ BASIC MODULE: PROGRAM -------------------------------------------------
        ///
        ///subcall PROGRAM.ARGUMENTCOUNT  // F
        ///{
        ///	OUT_F result
        ///	MOVE8_F 0 result
        ///}
        ///
        ///subcall PROGRAM.DIRECTORY  // S
        ///{
        ///	OUT_S result 128
        ///	FILENAME(GET_FOLDERNAME,127,result)
        ///}
        ///
        ///subcall PROGRAM.GETARGUMENT  // FF
        ///{
        ///	IN_F index
        ///	OUT_S result 8
        ///	STRINGS DUPLICATE &apos;&apos; result
        ///}
        ///
        ///
        ///inline PROGRAM.DELAY    // FV
        ///{
        ///	DATA32 milliseconds:#
        ///	MOVEF_32 :0 milliseconds:#
        ///	DATA32 timer:#
        ///	TIM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///// This method uses the property of the VM, that a subcall can not be 
        ///// re-called by a thread while it is still running in another thread.
        ///// It does an atomic get and increment action, incrementing a counter 
        ///// and returning the original value in a seperate (thread-local) variable
        ///subcall GETANDINC32     // V
        ///{
        ///	IN_32 counterin
        ///	IN_32 inc
        ///	OUT_32 counterout
        ///	OUT_32 prev
        ///
        ///	MOVE32_32 counterin prev
        ///	ADD32 counterin inc counterout
        ///}
        ///
        ///
        ///subcall EQ_STRING       // SSS
        ///{
        ///	IN_S  a 252
        ///	IN_S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string runtimelibrary {
            get {
                return ResourceManager.GetString("runtimelibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // -------------------------------------------------- EV3 MODULE: SENSOR -----------------------------------
        ///
        ///subcall SENSOR.GETNAME		// FS
        ///{
        ///	IN_F port
        ///	OUT_S result 32
        ///	
        ///	DATA8 layer
        ///	DATA8 no
        ///	
        ///	MOVEF_8 port no
        ///	SUB8 no 1 no
        ///	DIV8 no 4 layer
        ///	MATH MOD8 no 4 no
        ///	
        ///	INPUT_DEVICE GET_NAME layer no 32 result
        ///	STRINGS STRIP result result
        ///}
        ///
        ///subcall SENSOR.GETTYPE		// FF
        ///{
        ///	IN_F port
        ///	OUT_F result
        ///	
        ///	DATA8 layer
        ///	DATA8 no
        ///	DATA8 type
        ///	DATA8 mode
        ///	
        ///	MOVEF_8 port no
        ///	SUB8 no 1 no
        ///	D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------ EV3 MODULE: SPEAKER -------------------------------------------------
        ///
        ///inline SPEAKER.STOP      // V
        ///{
        ///	SOUND BREAK
        ///}
        ///
        ///subcall SPEAKER.TONE      // FFFV
        ///{
        ///	IN_F volume
        ///	IN_F tone
        ///	IN_F duration
        ///	
        ///	DATA8 vol
        ///	DATA16 tne
        ///	DATA16 dur
        ///	MOVEF_8 volume vol
        ///	MOVEF_16 tone tne
        ///	MOVEF_16 duration dur
        ///	
        ///	SOUND TONE vol tne dur
        ///}
        ///
        ///subcall SPEAKER.NOTE      // FSFV
        ///{
        ///	IN_F volume
        ///	IN_S note 8
        ///	IN_F duration
        ///	
        ///	DATA8 vol
        ///	DATA16 tne
        ///	DATA16 dur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------ BASIC MODULE: TEXT ---------------------------------------------------
        ///
        ///subcall TEXT.APPEND     // SSS
        ///{
        ///	IN_S a 252
        ///	IN_S b 252
        ///    OUT_S result 252
        ///	
        ///	DATA16 len0
        ///	DATA16 len1
        ///	DATA16 sum
        ///
        ///	STRINGS GET_SIZE a len0
        ///	STRINGS GET_SIZE b len1
        ///	ADD16 len0,len1,sum
        ///	JR_GT16 sum,251,stringsizeexceeded
        ///
        ///	STRINGS ADD a b result
        ///	RETURN
        ///	
        ///stringsizeexceeded:	
        ///    STRINGS DUPLICATE a result
        ///}
        ///
        ///subcall TEXT.CONVERTTOLOWERCASE  // SS
        ///{
        ///	IN_S a 252 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inline THREAD.YIELD  // V
        ///{
        ///	SLEEP
        ///}
        ///.
        /// </summary>
        internal static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // -------------------------------------- EXTENSION MODULE: VECTOR --------------------------------------------
        ///
        ///subcall VECTOR.INIT       // FFA
        ///{
        ///	IN_F size
        ///	IN_F value
        ///	IN_16 a
        ///
        ///	DATA32 size32
        ///	MOVEF_32 size size32
        ///	JR_LTEQ32 size32 0 empty
        ///
        ///	ARRAY RESIZE a size32
        ///	ARRAY FILL a value
        ///	RETURN
        ///
        ///empty:
        ///    ARRAY RESIZE a 0
        ///}
        ///
        ///subcall VECTOR.ADD        // FAAA
        ///{
        ///	IN_F size
        ///	IN_16 a
        ///	IN_16 b
        ///	IN_16 c
        ///
        ///	DATA32 sizea
        ///	DATA32 sizeb
        ///	ARRAY SIZE a sizea
        ///	ARRAY SIZE b sizeb
        ///
        ///	DATA32  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vector {
            get {
                return ResourceManager.GetString("Vector", resourceCulture);
            }
        }
    }
}
